### ISSUE TITLE
pseudoStates with the same name

### ISSUE THREAD

**Issue by jaquintano** [klangfarbe/UML-Statechart-Framework-for-Java#4]
Hi,

We have detected a problem related with the names of startStates.

In the following example, 2 startStates (marked with notes) have the same name. The effect is that when you go from "EquipoDesconectado" to "EtapaConfiguracion", the internal transition to "EnviandoAtributos" never happen.

If we change the name of the startState to be unique, the problem disappears.

![pseudoStates](https://f.cloud.github.com/assets/3480187/276251/62be5acc-90a7-11e2-802c-820d3f69506f.jpg)

**Comment by captainmeeple** [comment]
Hi, 

I cannot reproduce this issue. Regarding the implementation, it is not possible to have a state with the same name. This will result in an exception. 

If this issue still exists, please provide a unittest for testing.

Best regards,
Chris
