### ISSUE TITLE
A little bit of FRP

### ISSUE THREAD

**Issue by akond** [klangfarbe/UML-Statechart-Framework-for-Java#7]
I'm trying to use your library from Clojure (via a wrapper). It works fine, but I use a reactive framework, and I would like to bind an event handler on every state transition in Metadata.

I've been thinking about extending Metadata class, but the `activate` method is visible only from the package it is in.

Would you be able to amend this class a little bit, so it accepts a handler, which is to be called when a new state settles in?

**Comment by klangfarbe** [comment]
Hi, 

I have ditched Java-Development some years ago. So to be honest, the lib is more or less "as-is" and most likely it could be updated with more "modern" Java I am pretty sure :D  Still, if you have wished or ideas, feel free to modify the code and I am happy to update it here :)

Best regards,
Chris
